#!/bin/bash

dig slash16.org | grep SERVER | awk '{print $3}' | awk -F [()]' '{print $2}'

# dig query DNS for address
# search for server part
# -F defines input field separators as regexp
# so we print second value placed between circle brackets

# nslookup slash16.org 
